export const categories = [
  "Restaurantes y bares",
  "Tiendita",
  "Despensa / supermercado",
  "Entretenimiento",
  "Viajes",
  "Transporte",
  "Deporte",
  "Compras personales",
  "Software y suscripciones",
  "Salud",
  "ITAM",
  "Entrenamiento",
  "Binance (salarios)",
  "Club Amigos / Proyectos",
  "Comisiones y finanzas",
  "Otros / Por revisar",
];
