import { PDF_READER_VERSION } from "./pdfImport.ts";
import type { Statement, Transaction } from "./types.ts";

const MIGRATION_TOLERANCE = 0.05;

/**
 * Makes persisted statements safe across parser revisions.
 *
 * A statement produced by an older reader cannot be trusted retroactively:
 * its rows may contain exactly the extraction error the new reader fixed.
 * Keep the document visible for audit, but quarantine it until the source PDF
 * is imported again with the current reader contract.
 */
export function prepareStoredStatements(
  statements: Statement[],
  readerVersion = PDF_READER_VERSION,
) {
  return statements.map((statement) => {
    const hasReconciliation = Boolean(statement.reconciliationStatus && statement.reconciliation);
    const isCurrentReader = statement.readerVersion === readerVersion;
    if (hasReconciliation && isCurrentReader) return statement;

    const reason = !statement.readerVersion
      ? "Estado importado antes de la conciliación automática; vuelve a importarlo para usarlo en los KPI."
      : !isCurrentReader
        ? `Estado generado con el lector ${statement.readerVersion}; vuelve a importar el PDF con ${readerVersion}.`
        : "Estado sin evidencia de conciliación completa; vuelve a importarlo para usarlo en los KPI.";

    return {
      ...statement,
      status: "review" as const,
      reconciliationStatus: "pending" as const,
      reconciliation: {
        status: "pending" as const,
        tolerance: MIGRATION_TOLERANCE,
        reason,
      },
    };
  });
}

/**
 * Rebuild the persisted web ledger boundary after a reader update.
 *
 * Rows generated by a previous PDF reader are not recoverable from the row
 * itself: they may contain the exact malformed amount the new reader fixes.
 * Remove those PDF-derived rows from the stored collection while retaining
 * the statement metadata for the audit screen. Manual rows (without a
 * statementId) are intentionally preserved. Current-reader statements that
 * are merely pending OCR review stay available for explicit confirmation.
 */
export function prepareStoredLedger(
  statements: Statement[],
  transactions: Transaction[],
  readerVersion = PDF_READER_VERSION,
) {
  const preparedStatements = prepareStoredStatements(statements, readerVersion);
  const quarantinedStatementIds = new Set(
    statements
      .filter((statement) => (
        statement.readerVersion !== readerVersion
        || !statement.reconciliationStatus
        || !statement.reconciliation
      ))
      .map((statement) => statement.id),
  );
  const retainedTransactions = transactions.filter((transaction) => (
    !transaction.statementId || !quarantinedStatementIds.has(transaction.statementId)
  ));
  return {
    statements: preparedStatements,
    transactions: retainedTransactions,
    quarantinedStatementIds: [...quarantinedStatementIds],
    quarantinedMovementCount: transactions.length - retainedTransactions.length,
  };
}
