import { PDF_READER_VERSION } from "./pdfImport.ts";
import type { Statement, Transaction } from "./types.ts";

const MIGRATION_TOLERANCE = 0.05;

/**
 * Makes persisted statements safe across parser revisions.
 *
 * A statement produced by an older reader cannot be trusted retroactively:
 * its rows may contain exactly the extraction error the new reader fixed.
 * Keep the document visible for audit, but quarantine it until the source PDF
 * is imported again with the current reader contract.
 */
export function prepareStoredStatements(
  statements: Statement[],
  readerVersion = PDF_READER_VERSION,
) {
  return statements.map((statement) => {
    const hasReconciliation = Boolean(statement.reconciliationStatus && statement.reconciliation);
    const isCurrentReader = statement.readerVersion === readerVersion;
    // A statement that is already ready must also carry verified issuer
    // evidence.  Earlier reader versions could mark a file ready from a
    // filename-only guess (or leave the field absent entirely); allowing that
    // row into the canonical ledger would let a BBVA PDF masquerade as a
    // Santander account even when its totals happen to reconcile.
    const sourceNeedsReview = statement.status === "ready"
      && statement.sourceDetection?.status !== "verified"
      && statement.issuerConfirmedByUser !== true;
    if (hasReconciliation && isCurrentReader && !sourceNeedsReview) return statement;

    const reason = !statement.readerVersion
      ? "Estado importado antes de la conciliación automática; vuelve a importarlo para usarlo en los KPI."
      : !isCurrentReader
        ? `Estado generado con el lector ${statement.readerVersion}; vuelve a importar el PDF con ${readerVersion}.`
        : sourceNeedsReview
          ? "Estado sin evidencia institucional verificada del emisor; vuelve a importarlo para confirmar el banco antes de usarlo en los KPI."
        : "Estado sin evidencia de conciliación completa; vuelve a importarlo para usarlo en los KPI.";

    return {
      ...statement,
      status: "review" as const,
      reconciliationStatus: "pending" as const,
      reconciliation: {
        status: "pending" as const,
        tolerance: MIGRATION_TOLERANCE,
        reason,
      },
    };
  });
}

/**
 * Rebuild the persisted web ledger boundary after a reader update.
 *
 * Rows generated by a previous PDF reader are not recoverable from the row
 * itself: they may contain the exact malformed amount the new reader fixes.
 * Remove those PDF-derived rows from the stored collection while retaining
 * the statement metadata for the audit screen. Manual rows (without a
 * statementId) are intentionally preserved. Current-reader statements that
 * are merely pending OCR review stay available for explicit confirmation.
 */
export function prepareStoredLedger(
  statements: Statement[],
  transactions: Transaction[],
  readerVersion = PDF_READER_VERSION,
) {
  const preparedStatements = prepareStoredStatements(statements, readerVersion);
  const quarantinedStatementIds = new Set(
    statements
      .filter((statement) => {
        const currentPending = statement.readerVersion === readerVersion
          && statement.status === "review"
          && statement.reconciliationStatus !== "valid";
        return !currentPending && (
          statement.readerVersion !== readerVersion
          || !statement.reconciliationStatus
          || !statement.reconciliation
          || (statement.status === "ready"
            && statement.sourceDetection?.status !== "verified"
            && statement.issuerConfirmedByUser !== true)
        );
      })
      .map((statement) => statement.id),
  );
  const retainedTransactions = transactions.filter((transaction) => (
    !transaction.statementId || !quarantinedStatementIds.has(transaction.statementId)
  ));
  return {
    statements: preparedStatements,
    transactions: retainedTransactions,
    quarantinedStatementIds: [...quarantinedStatementIds],
    quarantinedMovementCount: transactions.length - retainedTransactions.length,
  };
}
